"""empty message

Revision ID: 15d9de83cc7f
Revises: abcfa481d7ec
Create Date: 2022-11-01 14:28:09.032430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15d9de83cc7f'
down_revision = 'abcfa481d7ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'creator_userId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('event_ibfk_1', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['creator_userId'], ['userId'], ondelete='CASCADE')
    op.drop_constraint('participant_ibfk_1', 'participant', type_='foreignkey')
    op.drop_constraint('participant_ibfk_2', 'participant', type_='foreignkey')
    op.create_foreign_key(None, 'participant', 'event', ['event_eventId'], ['eventId'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participant', 'user', ['user_userId'], ['userId'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.create_foreign_key('participant_ibfk_2', 'participant', 'user', ['user_userId'], ['userId'])
    op.create_foreign_key('participant_ibfk_1', 'participant', 'event', ['event_eventId'], ['eventId'])
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_ibfk_1', 'event', 'user', ['creator_userId'], ['userId'])
    op.alter_column('event', 'creator_userId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
