"""empty message

Revision ID: abcfa481d7ec
Revises: 
Create Date: 2022-10-27 11:02:53.957557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcfa481d7ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=False),
    sa.Column('lastName', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('event',
    sa.Column('eventId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('aboutEvent', sa.String(length=255), nullable=True),
    sa.Column('startDate', sa.DATE(), nullable=False),
    sa.Column('endDate', sa.DATE(), nullable=False),
    sa.Column('startTime', sa.String(length=5), nullable=True),
    sa.Column('endTime', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['creator_userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('eventId')
    )
    op.create_table('participant',
    sa.Column('user_userId', sa.Integer(), nullable=True),
    sa.Column('event_eventId', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['event_eventId'], ['event.eventId'], ),
    sa.ForeignKeyConstraint(['user_userId'], ['user.userId'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
